name: event_commander
description: An EventBus, EventQueue, Command Pattern, and Undo-Redo library
version: 0.1.5
homepage: https://github.com/oblique63/EventCommander
author: Enrique Gavidia <enrique@enriquegavidia.com>

dev_dependencies:
  unittest: any
  browser: any
