name: event_commander
description: An EventBus, EventQueue, Command Pattern, and Undo-Redo library
version: 0.1.8+3
homepage: http://oblique63.github.io/EventCommander/
author: Enrique Gavidia <enrique@enriquegavidia.com>

dev_dependencies:
  unittest: any
  browser: any